### ISSUE TITLE
Missing key value in errors

### ISSUE THREAD

**Issue by satchinjoshi** [Workpop/graphql-utils#9]
Hi there, this is very nice tool. All things seems to be working great. But I have a field in `errors` called `validation` which I cannot access.

By default it give me:

```json
{
  "data": {
    "signup": null
  },
  "errors": [
    {
      "message": "validation"
    }
  ]
}
```

I am able to access `location` and `path` by using `errorFormatter`:
```js
  errorFormatter: (e) => {
    return e;
  }
```

```json
{
  "data": {
    "signup": null
  },
  "errors": [
    {
      "message": "validation",
      "locations": [
        {
          "line": 37,
          "column": 3
        }
      ],
      "path": [
        "signup"
      ]
    }
  ]
}
```

It would be great if someone would guide me on getting that `validation` field in errors.

**Comment by satchinjoshi** [comment]
If I do not use the proxy I get
```
{
  "data": {
    "signup": null
  },
  "errors": [
    {
      "message": "validation",
      "locations": [
        {
          "line": 37,
          "column": 3
        }
      ],
      "validation": [
        "email": ["Email already exits"]
      ]
    }
  ]
}
```

**Comment by abhiaiyer91** [comment]
This is because graphql-tools does not forward that error up to the proxy. We’re not actively fixing this now but if you can figure out how to forward them we can accept a PR! Thanks!
